version: '3.8'

services: 
  app:
    # build: .
    image: gabuuu2025/entregafinalm3:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=${MONGO_URI}
      - SECRET_JWT=${SECRET_JWT}
      - GOOGLE_EMAIL=alejandroalahi@gmail.com
      - PASSWORD_GOOGLE_APP=12345
#     volumes:
#       - ./:/app
#       - /app/node_modules
#     networks:
#       - app-coder-network

# networks:
#   app-coder-network:
#     driver: bridge
